os: windows
language: node_js
node_js:
   - lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
env:
  # Fix Windows build never ending in Travis CI
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

script:
  - |
      yarn install;
      yarn run publish;


branches:
  only:
  - master
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
