os: windows
language: node_js
node_js:
   - lts/*
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - |
      yarn install;
      yarn run publish;


branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
